const express = require('express')
const router = express.Router()
const { checkJwt } = require('../middlewares')

const controller = require('../controllers/animal')

router.get('/group', [checkJwt.checkToken],controller.getAnimalGroup)
router.post('/group', [checkJwt.checkToken],controller.addAnimalGroup)
router.put('/group', [checkJwt.checkToken],controller.updateAnimalGroup)
router.get('/animal', [checkJwt.checkToken],controller.getAnimal)
router.post('/animal', [checkJwt.checkToken], controller.addAnimal)
router.put('/animal', [checkJwt.checkToken],controller.updateAnimal)
router.get('/balance', [checkJwt.checkToken],controller.getBalanceCardAnimal)
router.post('/balance', [checkJwt.checkToken], controller.addBalanceCardAnimal)
router.put('/balance', [checkJwt.checkToken],controller.updateBalanceCardAnimal)
// Процессы
router.get('/registration', [checkJwt.checkToken],controller.getRegistratedAnimals)
router.post('/registration', [checkJwt.checkToken], controller.addRegistratedAnimals)
router.put('/registration', [checkJwt.checkToken],controller.updateRegistratedAnimals)
router.get('/off_spring', [checkJwt.checkToken],controller.getOffspring)
router.post('/off_spring', [checkJwt.checkToken], controller.addOffspring)
router.put('/off_spring', [checkJwt.checkToken],controller.updateOffspring)
router.get('/weight_gain', [checkJwt.checkToken],controller.getWeightGain)
router.post('/weight_gain', [checkJwt.checkToken], controller.addWeightGain)
router.put('/weight_gain', [checkJwt.checkToken],controller.updateWeightGain)
router.get('/transfer', [checkJwt.checkToken],controller.getAnimalTransfer)
router.post('/transfer', [checkJwt.checkToken], controller.addAnimalTransfer)
router.put('/transfer', [checkJwt.checkToken],controller.updateAnimalTransfer)
router.get('/milking', [checkJwt.checkToken],controller.getMilking)
router.post('/milking', [checkJwt.checkToken], controller.addMilking)
router.put('/milking', [checkJwt.checkToken],controller.updateMilking)

router.get('/feed_write', [checkJwt.checkToken],controller.getFeedWriteOff)
router.post('/feed_write', [checkJwt.checkToken], controller.addFeedWriteOff)
router.put('/feed_write', [checkJwt.checkToken],controller.updateFeedWriteOff)
module.exports = router